#!/usr/bin/env bash
wget http://octodex.github.com/images/octoliberty.png 
wget http://octodex.github.com/images/femalecodertocat.png 
wget http://octodex.github.com/images/daftpunktocat-thomas.gif 
wget http://octodex.github.com/images/daftpunktocat-guy.gif 
wget http://octodex.github.com/images/foundingfather_v2.png 
wget http://octodex.github.com/images/poptocat_v2.png 
wget http://octodex.github.com/images/Mardigrastocat.png 
wget http://octodex.github.com/images/kimonotocat.png 
wget http://octodex.github.com/images/Professortocat_v2.png 
wget http://octodex.github.com/images/goretocat.png 
wget http://octodex.github.com/images/FIRSTocat.png 
wget http://octodex.github.com/images/motherhubbertocat.png 
wget http://octodex.github.com/images/skitchtocat.png 
wget http://octodex.github.com/images/gangnamtocat.png 
wget http://octodex.github.com/images/droctocat.png 
wget http://octodex.github.com/images/spidertocat.png 
wget http://octodex.github.com/images/megacat-2.png 
wget http://octodex.github.com/images/dodgetocat_v2.png 
wget http://octodex.github.com/images/stormtroopocat.png 
wget http://octodex.github.com/images/pusheencat.png 
wget http://octodex.github.com/images/deckfailcat.png 
wget http://octodex.github.com/images/murakamicat.png 
wget http://octodex.github.com/images/homercat.png 
wget http://octodex.github.com/images/minion.png 
wget http://octodex.github.com/images/droidtocat.png 
wget http://octodex.github.com/images/octofez.png 
wget http://octodex.github.com/images/heisencat.png 
wget http://octodex.github.com/images/red-polo.png 
wget http://octodex.github.com/images/twenty-percent-cooler-octocat.png 
wget http://octodex.github.com/images/momtocat.png 
wget http://octodex.github.com/images/front-end-conftocat.png 
wget http://octodex.github.com/images/snowoctocat.png 
wget http://octodex.github.com/images/electrocat.png 
wget http://octodex.github.com/images/aidorucat.png 
wget http://octodex.github.com/images/codercat.jpg 
wget http://octodex.github.com/images/strongbadtocat.png 
wget http://octodex.github.com/images/adventure-cat.png 
wget http://octodex.github.com/images/doctocat-brown.jpg 
wget http://octodex.github.com/images/dojocat.jpg 
wget http://octodex.github.com/images/defunktocat.png 
wget http://octodex.github.com/images/herme-t-crabb.png 
wget http://octodex.github.com/images/saint-nicktocat.jpg 
wget http://octodex.github.com/images/orderedlistocat.png 
wget http://octodex.github.com/images/thanktocat.png 
wget http://octodex.github.com/images/megacat.jpg 
wget http://octodex.github.com/images/linktocat.jpg 
wget http://octodex.github.com/images/plumber.jpg 
wget http://octodex.github.com/images/octotron.jpg 
wget http://octodex.github.com/images/baracktocat.jpg 
wget http://octodex.github.com/images/octocat-de-los-muertos.jpg 
wget http://octodex.github.com/images/grim-repo.jpg 
wget http://octodex.github.com/images/father_timeout.jpg 
wget http://octodex.github.com/images/waldocat.png 
wget http://octodex.github.com/images/hipster-partycat.jpg 
wget http://octodex.github.com/images/riddlocat.png 
wget http://octodex.github.com/images/visionary.jpg 
wget http://octodex.github.com/images/oktobercat.png 
wget http://octodex.github.com/images/shoptocat.png 
wget http://octodex.github.com/images/nyantocat.gif 
wget http://octodex.github.com/images/octdrey-catburn.jpg 
wget http://octodex.github.com/images/spectrocat.png 
wget http://octodex.github.com/images/bear-cavalry.png 
wget http://octodex.github.com/images/andycat.jpg 
wget http://octodex.github.com/images/notocat.jpg 
wget http://octodex.github.com/images/dodgetocat.jpg 
wget http://octodex.github.com/images/cloud.jpg 
wget http://octodex.github.com/images/scarletteocat.jpg 
wget http://octodex.github.com/images/poptocat.png 
wget http://octodex.github.com/images/jenktocat.jpg 
wget http://octodex.github.com/images/xtocat.jpg 
wget http://octodex.github.com/images/chellocat.jpg 
wget http://octodex.github.com/images/cherryontop-o-cat.png 
wget http://octodex.github.com/images/supportcat.png 
wget http://octodex.github.com/images/collabocats.jpg 
wget http://octodex.github.com/images/constructocat2.jpg 
wget http://octodex.github.com/images/total-eclipse-of-the-octocat.jpg 
wget http://octodex.github.com/images/pacman-ghosts.jpg 
wget http://octodex.github.com/images/okal-eltocat.jpg 
wget http://octodex.github.com/images/octoclark-kentocat.jpg 
wget http://octodex.github.com/images/agendacat.png 
wget http://octodex.github.com/images/ironcat.jpg 
wget http://octodex.github.com/images/inspectocat.jpg 
wget http://octodex.github.com/images/jean-luc-picat.jpg 
wget http://octodex.github.com/images/spocktocat.png 
wget http://octodex.github.com/images/wilson.jpg 
wget http://octodex.github.com/images/swagtocat.png 
wget http://octodex.github.com/images/drunktocat.jpg 
wget http://octodex.github.com/images/dolla-dolla-bill-yall.jpg 
wget http://octodex.github.com/images/hubot.jpg 
wget http://octodex.github.com/images/monroe.jpg 
wget http://octodex.github.com/images/trekkie.png 
wget http://octodex.github.com/images/octonaut.jpg 
wget http://octodex.github.com/images/bouncercat.png 
wget http://octodex.github.com/images/founding-father.jpg 
wget http://octodex.github.com/images/pythocat.png 
wget http://octodex.github.com/images/drupalcat.jpg 
wget http://octodex.github.com/images/socialite.jpg 
wget http://octodex.github.com/images/setuptocat.jpg 
wget http://octodex.github.com/images/repo.png 
wget http://octodex.github.com/images/forktocat.jpg 
wget http://octodex.github.com/images/benevocats.png 
wget http://octodex.github.com/images/scottocat.jpg 
wget http://octodex.github.com/images/puppeteer.png 
wget http://octodex.github.com/images/octobiwan.jpg 
wget http://octodex.github.com/images/class-act.png 
wget http://octodex.github.com/images/original.png 